Fp solution
nurgeld/ru-study-ruby pull request #3
Opened 2022-10-04 16:35 UTC by nurgeld

2022-10-05 07:30 UTC, greybutton requested changes
чот здесь код от другого задания

2022-10-06 17:34 UTC, nurgeld commented
> чот здесь код от другого задания

Не понимаю как коммиты из другой ветки попали в текущую. Код для задания fp я делал в ветке `fp-solution`. Два последних коммита запушил в гитхаб в соответствующую ветку `fp-solution`. После ревью, сегодня пытался удалить прошлые (ненужные в данной ветке) коммиты с помощью rebase - но он мне отображал только два последних корректных коммита.
Сделал в итоге` git push -f` - после чего из пуллреквеста ненужные коммиты пропали. Обрадовался, но потом заметил, что в самом коде данной ветки все еще есть код задания arrays.. Но как он там появился, непонятно

2022-10-06 18:19 UTC, nurgeld commented
кажется понял свою ошибку. даже переключившись на локальную ветку fp-solution я выполнял команды гита (а именно `git add .` ) из корневой папки. И скорее всего в стейдж попали изменения над файлами прошлого задания. Хотя я не помню - правил ли я их) Но другого объяснения не вижу

2022-10-08 09:15 UTC, greybutton approved these changes

2022-10-08 16:31 UTC, merged